//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bricks.SMS.Nexmo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bricks.SMS.Nexmo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LetsShare.
        /// </summary>
        internal static string Nexmo_SenderId {
            get {
                return ResourceManager.GetString("Nexmo_SenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not enabled for REST.
        /// </summary>
        internal static string NexmoResponseCode_AccountNotEnabledForREST {
            get {
                return ResourceManager.GetString("NexmoResponseCode_AccountNotEnabledForREST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is not provisioned for REST submission, you should use SMPP instead.
        /// </summary>
        internal static string NexmoResponseCode_AccountNotEnabledForREST_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_AccountNotEnabledForREST_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Failed.
        /// </summary>
        internal static string NexmoResponseCode_CommunicationFailed {
            get {
                return ResourceManager.GetString("NexmoResponseCode_CommunicationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was not submitted because there was a communication failure.
        /// </summary>
        internal static string NexmoResponseCode_CommunicationFailed_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_CommunicationFailed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility not allowed.
        /// </summary>
        internal static string NexmoResponseCode_FacilityNotAllowed {
            get {
                return ResourceManager.GetString("NexmoResponseCode_FacilityNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request makes use of a facility that is not enabled on your account.
        /// </summary>
        internal static string NexmoResponseCode_FacilityNotAllowed_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_FacilityNotAllowed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string NexmoResponseCode_InternalError {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred in the Nexmo platform whilst processing this message.
        /// </summary>
        internal static string NexmoResponseCode_InternalError_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InternalError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        internal static string NexmoResponseCode_InvalidCredentials {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The api_key / api_secret you supplied is either invalid or disabled.
        /// </summary>
        internal static string NexmoResponseCode_InvalidCredentials_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidCredentials_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message.
        /// </summary>
        internal static string NexmoResponseCode_InvalidMessage {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nexmo platform was unable to process this message, for example, an un-recognized number prefix or the number is not whitelisted if your account is new.
        /// </summary>
        internal static string NexmoResponseCode_InvalidMessage_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NexmoResponseCode_InvalidMessageClass.
        /// </summary>
        internal static string NexmoResponseCode_InvalidMessageClass {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidMessageClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message class value supplied was out of range (0 - 3).
        /// </summary>
        internal static string NexmoResponseCode_InvalidMessageClass_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidMessageClass_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid params.
        /// </summary>
        internal static string NexmoResponseCode_InvalidParams {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of one or more parameters is invalid.
        /// </summary>
        internal static string NexmoResponseCode_InvalidParams_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidParams_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sender address.
        /// </summary>
        internal static string NexmoResponseCode_InvalidSenderAddress {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidSenderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender address (from parameter) was not allowed for this message. Restrictions may apply depending on the destination see our FAQs.
        /// </summary>
        internal static string NexmoResponseCode_InvalidSenderAddress_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidSenderAddress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Signature.
        /// </summary>
        internal static string NexmoResponseCode_InvalidSignature {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was not submitted due to a verification failure in the submitted signature.
        /// </summary>
        internal static string NexmoResponseCode_InvalidSignature_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidSignature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TTL.
        /// </summary>
        internal static string NexmoResponseCode_InvalidTTL {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidTTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ttl parameter values is invalid.
        /// </summary>
        internal static string NexmoResponseCode_InvalidTTL_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_InvalidTTL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message too long.
        /// </summary>
        internal static string NexmoResponseCode_MessageTooLong {
            get {
                return ResourceManager.GetString("NexmoResponseCode_MessageTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to Binary submissions, where the length of the UDH and the message body combined exceed 140 octets.
        /// </summary>
        internal static string NexmoResponseCode_MessageTooLong_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_MessageTooLong_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing params.
        /// </summary>
        internal static string NexmoResponseCode_MissingParams {
            get {
                return ResourceManager.GetString("NexmoResponseCode_MissingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request is incomplete and missing some mandatory parameters.
        /// </summary>
        internal static string NexmoResponseCode_MissingParams_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_MissingParams_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number barred.
        /// </summary>
        internal static string NexmoResponseCode_NumberBarred {
            get {
                return ResourceManager.GetString("NexmoResponseCode_NumberBarred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number you are trying to submit to is blacklisted and may not receive messages.
        /// </summary>
        internal static string NexmoResponseCode_NumberBarred_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_NumberBarred_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner account barred.
        /// </summary>
        internal static string NexmoResponseCode_PartnerAccountBarred {
            get {
                return ResourceManager.GetString("NexmoResponseCode_PartnerAccountBarred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The api_key you supplied is for an account that has been barred from submitting messages.
        /// </summary>
        internal static string NexmoResponseCode_PartnerAccountBarred_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_PartnerAccountBarred_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner quota exceeded.
        /// </summary>
        internal static string NexmoResponseCode_PartnerQuotaExceeded {
            get {
                return ResourceManager.GetString("NexmoResponseCode_PartnerQuotaExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pre-pay account does not have sufficient credit to process this message.
        /// </summary>
        internal static string NexmoResponseCode_PartnerQuotaExceeded_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_PartnerQuotaExceeded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string NexmoResponseCode_Success {
            get {
                return ResourceManager.GetString("NexmoResponseCode_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message was successfully accepted for delivery by Nexmo.
        /// </summary>
        internal static string NexmoResponseCode_Success_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_Success_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttled.
        /// </summary>
        internal static string NexmoResponseCode_Throttled {
            get {
                return ResourceManager.GetString("NexmoResponseCode_Throttled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the submission capacity allowed on this account, please back-off and retry.
        /// </summary>
        internal static string NexmoResponseCode_Throttled_Description {
            get {
                return ResourceManager.GetString("NexmoResponseCode_Throttled_Description", resourceCulture);
            }
        }
    }
}
